trigger: none
pr: none # PR Trigger

resources:
  repositories:
    - repository: EnvironmentAutomation
      type: github
      name: NetworkContractSolutions/EnvironmentAutomation
      ref: refs/heads/main
      endpoint: NContractsGithub

#variables that are defined in the pipeline
#AzureResourceManagerSC: <Name of the Azure Resource Manager service connection>

stages:
- stage: EnvironmentTest
  displayName: Environment Test
  dependsOn: []
  jobs:
  - job: EnvironmentTest
    pool:
      name: 'WindowsAgents'
      demands: TestAgentSupport
    displayName: Environment Test
    steps:
    - template: 'Templates/Tasks/TAStart1.yml@EnvironmentAutomation'
      parameters:
        AzureResourceManagerSC: '$(AzureResourceManagerSC)'

    # - template: 'Templates/Tasks/TADeployRelease1.yml@EnvironmentAutomation'
    #   parameters:
    #     AzureResourceManagerSC: '$(AzureResourceManagerSC)'
    #     ProjectName: "Data Explorer"
    #     ReleaseVersion: "${{ parameters.releaseVersion }}"

    - task: AzureCLI@2
      displayName: 'Display Environment Variables'
      inputs:
        azureSubscription: '$(AzureResourceManagerSC)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          $envVars = Get-ChildItem Env:
          $taEnvVars = $envVars | Where-Object { $_.Name -like 'TA_*' }

          foreach ($var in $taEnvVars) {
              Write-Host "$($var.Name): $($var.Value)"
          }

    - template: 'Templates/Tasks/TAReset1.yml@EnvironmentAutomation'
      parameters:
        AzureResourceManagerSC: '$(AzureResourceManagerSC)'