trigger: none
pr: none # PR Trigger

#variables that are defined in the pipeline
#AzureResourceManagerSC: <Name of the Azure Resource Manager service connection>

stages:
- stage: EnvironmentTest
  displayName: Environment Test
  dependsOn: []
  jobs:
  - job: EnvironmentTest
    pool:
      name: 'WindowsAgents'
      demands: TestAgentSupport
    displayName: Environment Test
    steps:
    - task: AzureCLI@2
      displayName: 'Reset Test Agent'
      inputs:
        azureSubscription: '$(AzureResourceManagerSC)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          . c:\temp\ta-commands.ps1 
          
          $projectsToInclude = @('Authentication API','Authentication Service Host','Authentication UI','Customer Administration','Customer Adminstration UI','Document Service v2')
          Reset-TestAgent -projectsToInclude $projectsToInclude

    - task: AzureCLI@2
      displayName: 'Display Environment Variables'
      inputs:
        azureSubscription: '$(AzureResourceManagerSC)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          $envVars = Get-ChildItem Env:
          $taEnvVars = $envVars | Where-Object { $_.Name -like 'TA_*' }

          foreach ($var in $taEnvVars) {
              Write-Host "$($var.Name): $($var.Value)"
          }

