trigger: none
pr: none # PR Trigger

resources:
  repositories:
    - repository: EnvironmentAutomation
      type: github
      name: NetworkContractSolutions/EnvironmentAutomation
      ref: refs/heads/imagetag
      endpoint: 'NContractsGithub'

#variables that are defined in the pipeline
#AzureResourceManagerSC: <Name of the Azure Resource Manager service connection>

stages:
- stage: EnvironmentTest
  displayName: Environment Test
  dependsOn: []
  jobs:
  - job: EnvironmentTest
    pool:
      name: 'WindowsAgents'
      demands: TestAgentSupport
    displayName: Environment Test
    steps:
    - template: 'Templates/Tasks/ResetTestAgent1.yml@EnvironmentAutomation'
      parameters:
        AzureResourceManagerSC: '$(AzureResourceManagerSC)'
        ProjectToInclude: 'Authentication API,Authentication Service Host,Authentication UI,Customer Administration,Customer Adminstration UI,Document Service v2'

    - task: AzureCLI@2
      displayName: 'Display Environment Variables'
      inputs:
        azureSubscription: '$(AzureResourceManagerSC)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          Write-Host "TA_VMName: $env:TA_VMName"
          Write-Host "TA_ResourceGroup: $env:TA_ResourceGroup"
          Write-Host "TA_AuthUI: $env:TA_AuthUI"
          Write-Host "TA_AuthUI_Login: $env:TA_AuthUI_Login"
          Write-Host "TA_AuthAPI: $env:TA_AuthAPI"
          Write-Host "TA_EnvironmentName: $env:TA_EnvironmentName"
